---
- name: Deploy Ship Commander
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.postgresql
  tasks:
    - name: Update System
      yum:
        name: java-11-openjdk-headless
        enablerepo: postgresql:stream
        state: latest
        update_cache: true
    - name: Create ship-commander install location
      file:
        path: /opt/ship-commander
        state: directory
    - name: Deploy ship commander service
      copy:
        src: ship-commander.jar
        dest: /opt/ship-commander/ship-commander.jar
        mode: u+rwx
      register: shipcommcopy
    - name: Deploy ship commander unit
      copy:
        src: shipcomm.service
        dest: /etc/systemd/system/shipcomm.service
        mode: 0644
      register: shipcommunit
    - name: Reload systemd units
      systemd:
        daemon_reload: true
      when: shipcommunit.changed or shipcommcopy.changed
    - name: Start and enable shipcomm
      systemd:
        name: shipcomm
        state: restarted
      when: shipcommcopy.changed or shipcommunit.changed
